
package jsp.flightbooking.entity;

import java.time.LocalDate;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnore;


@Data
@Entity
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @CreationTimestamp
    private LocalDate paymentDate;

    private double amount; // generated by calculations
    @Enumerated(EnumType.STRING)
    private TransactionMode modeOfTransaction;
    
    @Enumerated(EnumType.STRING)
    private Status status;
    
    @JsonIgnore
    @JoinColumn(name = "booking_id")
    @OneToOne
    private Booking booking;
}
